services:
  postgres:
    container_name: postgres
    image: postgres:17.5
    hostname: postgres
    environment:
      - POSTGRES_USER=oeuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oe
    ports:
      - "5432:5432"
    volumes:
      - pg_volumeOE:/var/lib/postgresql/data
    networks:
      - oe-network

  restaurant:
    container_name: restaurant
    image: eclipse-temurin:21-jdk
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - ./restaurant/target/restaurant.jar:/app/restaurant.jar
    command: [ "java", "-jar", "restaurant.jar" ]
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/oe
      SPRING_DATASOURCE_USERNAME: oeuser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - oe-network


networks:
  oe-network:
    driver: bridge

volumes:
  pg_volumeOE:
