hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/oe
hibernate.connection.username=oeuser
hibernate.connection.password=password

hibernate.default_schema=public

# PostgreSQL dialect
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL logging
hibernate.show_sql=true
hibernate.format_sql=true

# Cache disabled (same as teacher style)
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_query_cache=false

# Field-based access (important for generated entities consistency)
hibernate.mapping.default-access=field