---
servers:
- url: "http://localhost:8080"
openapi: "3.0.0"
paths:
  /menu/gluten-free:
    $ref: "./restaurant.yaml#/paths/~1menu~1gluten-free"
  /menu/{id}:
    $ref: "./restaurant.yaml#/paths/~1menu~1{id}"
  paths:
    $ref: "./restaurant.yaml#/paths/paths"
  /menu:
    $ref: "./restaurant.yaml#/paths/~1menu"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
